### ISSUE TITLE
Is the import idempotent?

### ISSUE THREAD

**Issue by Ciantic** [jampe/kp2bw#1]
Nice work!

I have a question, is the importing idempotent? 

Meaning that if I run it second time it won't duplicate entries in the Bitwarden database?

Reason I ask is that if my import fails, or I want to import my database just in parts I won't have to think about duplicates if I ever import my whole database.

**Comment by jampe** [comment]
Good input. To be honest, I wasn't thinking about that. I always purged my Bitwarden vault prior to testing, so this never came up. 

I'll add a check to prevent this. Thanks for noting!

**Comment by Ciantic** [comment]
One way to do this would be to store KeePass UUID to a custom field and use it as a unique key. Not sure how easy that is.

**Comment by jampe** [comment]
Yeah this would be possible, however I don't wona bloat the new vault with references to the old KeePass db.

I went for a simple item by name lookup in the specific folder. This has the limitation that it could skip entries, should an entry with the same name already exist in the same folder prior to starting the import.
This is quite an edge case which is now documented here. Should this be a problem, I can extend the comparison to username / password / urls as well.
