### ISSUE TITLE
Attachments whose names have a blank won't import

### ISSUE THREAD

**Issue by hrvylein** [jampe/kp2bw#15]
When importing file attachments that contain a blank won't get imported and no error message is thrown.

Adding "" to the filename in https://github.com/jampe/kp2bw/blob/e6a321b23163add06cb435ee2673ec88f2d10153/kp2bw/bitwardenclient.py#L120 makes it work.

**Comment by jampe** [comment]
should be fixed now. please report back if you still experience this problem
