### ISSUE TITLE
TOTP is imported as a custom field rather than being setup natively in bitwarden

### ISSUE THREAD

**Issue by meichthys** [jampe/kp2bw#24]
Currently the import sets the TOTP key to a custom field rather than the native bitwarden TOTP field:

![image](https://user-images.githubusercontent.com/10717998/155768876-f861cc16-4e7f-4653-9350-e13f02e67d0c.png)

**Comment by mcfisch** [comment]
I'm currently migrating from KeePassXC to Vaultwarden, and for me the TOTP settings don't make it into the vault at all, not even as a custom field. The OTP field is missing entirely. Adding it manually does work, but gets tedious if you have to do it for more than a handful of entries. Also I'm still purging/migrating/testing, so manual changes won't stick anyway.

BTW, I used the WHL file to install via PIP.

**Comment by jampe** [comment]
should work now thanks to @mcfisch
