### ISSUE TITLE
Import errors with "Special Characters"

### ISSUE THREAD

**Issue by pwood** [jampe/kp2bw#3]
Hello! Thanks for writing this, it's a missing tool that's really needed. I've come accross a couple of errors while importing data, 

`INFO: [17 of 391] Creating Bitwarden entry in Personal for XXXX backup...
ERROR: !! ERROR: Creation of entry failed: Error parsing the encoded request data. !!`

This entry has no username or password, but it has a Note (shorter than 1k). It also has [] brackets and a :.

INFO: [17 of 391] Creating Bitwarden entry in Personal for XXX root...
ERROR: !! ERROR: Creation of entry failed: /bin/sh: 1: Syntax error: EOF in backquote substitution`

This entry does contain a backtick, as well as other characters which would likely break a shell. If you really need I can change this password and release it to you for testing.

Cheers!

**Comment by jampe** [comment]
Thanks for reporting this and helping to improve this tool.

I'll push a fix in a few mins, please test it and report back if it worked for you, thanks!

**Comment by pwood** [comment]
Yup, that's got it, thanks very much. I've got another fix I'll raise as a pull request.
