### ISSUE TITLE
Bitwarden - No Folder - Throws Exception On Import

### ISSUE THREAD

**Issue by Sn3akyP3t3** [jampe/kp2bw#31]
**Describe the bug**
Looks like Bitwarden added a `No Folder` as a virtual folder that doesn't integrate well with kp2bw during import.  To make matters worse it seems Bitwarden lacks the ability to delete the `No Folder` once it has been created or it is always there so it should be handled regardless.

To recreate the scenario for testing simply create a Keepass password database and create passwords in the root of the database (no folders) and conduct an import with kp2bw into Bitwarden.

**Provide verbose program output**
I will not be providing verbose output of actual import attempts, but I will provide key points of information that highlights the problem or what I believe to be the problem.

The import produces the following error output:
```
INFO: Found 1596 entries in KeePass DB. Parsing now...
INFO: Parsed 1596 entries
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\FakePath\kp2bw\.env\kp2bw\Scripts\kp2bw.exe\__main__.py", line 7, in <module>
  File "C:\FakePath\kp2bw\.env\kp2bw\lib\site-packages\kp2bw\cli.py", line 69, in main
    c.convert()
  File "C:\FakePath\kp2bw\.env\kp2bw\lib\site-packages\kp2bw\convert.py", line 226, in convert
    self._create_bitwarden_items_for_entries()
  File "C:\FakePath\kp2bw\.env\kp2bw\lib\site-packages\kp2bw\convert.py", line 187, in _create_bitwarden_items_for_entries
    bw = BitwardenClient(self._bitwarden_password)
  File "C:\FakePath\kp2bw\.env\kp2bw\lib\site-packages\kp2bw\bitwardenclient.py", line 29, in __init__
    self._folders = {folder["name"]: folder["id"] for folder in json.loads(self._exec_with_session("bw list folders"))}
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

bw list folders
generates loads of folders along with the following:
```
    {
        "id": null,
        "name": "No Folder",
        "object": "folder"
    }
```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Python version:3.10.2
 - Bitwarden cli version: 2022 20 0

**Additional context**

**Comment by Sn3akyP3t3** [comment]
I will not be making a PR for this because I think its not the right way to resolve this, but I believe its a bad practice to have credentials stored in the root of the Keepass database so I moved the one that accidentally was placed there to another folder and then worked around the exception during import by changing the code in `bitwardenclient.py`.  If you keep stuff in the root of the Keepass database this is not a viable workaround for you:
 ```
        # get folder list
        # self._folders = {folder["name"]: folder["id"] for folder in json.loads(self._exec_with_session("bw list folders"))}
        self._folders = {folder["name"]: folder["id"] for folder in filter(lambda x: x['id'] is not None and x['Name'] == 'No Folder', json.loads(self._exec_with_session("bw list folders")))}
```

**Comment by aligator** [comment]
I got exactly the same error message, but for me it has nothing to do with the folder.

Instead it fails to authenticate to bitwarden if the password contains spaces due to no escaping:
https://github.com/jampe/kp2bw/blob/f8c50bd3fe115972ddbe453887d04a0026119f05/kp2bw/bitwardenclient.py#L20
the line should be
`        self._key = self._exec(f"bw unlock \"{password}\" --raw")`

if you use a password with spaces, it just writes nonsense into the result (no json) that's why it fails to parse.
Interestingly the error catcher there:
```
if "error" in self._key:
            raise Exception("Could not unlock the Bitwarden db. Is the Master Password correct and are bw cli tools set up correctly?")
```
does not catch anything.


However note: I use Vaultwarden! maybe with Bitwarden it would return something different...


I will create a simple PR which fixes the space-problem.

**Comment by jampe** [comment]
I'm closing this as it should be resoved by the PR #36. @Sn3akyP3t3 feel free to reopen the issue if you are still facing the problem.
