### ISSUE TITLE
Uploading attachments

### ISSUE THREAD

**Issue by marco90a** [jampe/kp2bw#43]
**Describe the bug**
Hi, I used the tool to import data within vaultwarden.

I imported all the credentials correctly but the file upload, although marked as done I can't find them in the vault.

Gone activated some other configuration?

**Desktop (please complete the following information):**
 - OS: Windows
 - Bitwarden cli version: 2023.5.0

**Comment by ambrozticar** [comment]
I have noticed this too with my vaultwarden import. I have reported it to vaultwarden and it seems to be an issue with the new bitwarden CLI versions. You can use the 2023.4.0 and it should work. The issue has been reported to https://github.com/bitwarden/clients/issues/5876

**Comment by jampe** [comment]
I'm closing this as its a problem with bitwarden and tracked there. Thanks for reporting anyway
