### ISSUE TITLE
Bitwarden supports nested folders

### ISSUE THREAD

**Issue by Chilinot** [jampe/kp2bw#5]
In the Readme it says that bitwarden does not support nested folders. But it does.

You create a nested folder in the following manner:
1. Create a root folder called `foo`
2. Create a new folder called `foo/bar`

Both the webclient and my OSX client interprets this structure as two folders, where `bar` resides withing `foo`.

**Comment by Chilinot** [comment]
You can find more information here: https://help.bitwarden.com/article/folders/

**Comment by jampe** [comment]
awesome, I somehow missied this feature in the documentation. I'll merge the PR asap. Thanks a lot!
